### ISSUE TITLE
When will the code be published? 

### ISSUE THREAD

**Issue by MagnumEnforcer** [wangsiwei2010/NeurIPS22-FMVACC#1]

**Comment by wangsiwei2010** [comment]
As with the same introduction, we will finish the work this weekend.

**Comment by wangsiwei2010** [comment]
Thanks for your issues. The code and introduction has been updated with an initialiation version. Any issue is welcomed.

**Comment by MagnumEnforcer** [comment]
Thank you!

**Comment by MagnumEnforcer** [comment]
NA
